// Generated by CoffeeScript 1.3.3
(function() {

  window.addEventListener('keydown', function(event) {
    if (event.altKey && event.which === 84) {
      return console.log("HOTKEY!");
    }
  });

}).call(this);
