// Generated by CoffeeScript 1.3.3
(function() {
  var closeTab, doHighlight, highlightTab, selectTab, tabs, template, updateLabel;

  selectTab = function(event) {
    var match;
    event.preventDefault();
    match = /(\d+)#(\d+)/.exec($(event.currentTarget).attr('href'));
    console.log("Switching to tab " + match[1] + " n window " + match[2]);
    chrome.windows.update(parseInt(match[1]), {
      focused: true
    });
    return chrome.tabs.update(parseInt(match[2]), {
      active: true
    });
  };

  highlightTab = function(event) {
    return doHighlight($(event.currentTarget));
  };

  doHighlight = function(tab) {
    if (tab[0] != null) {
      $('.tab.active').removeClass('active');
      return tab.addClass('active');
    }
  };

  closeTab = function(event) {
    var match;
    event.preventDefault();
    match = /(\d+)#(\d+)/.exec($(event.currentTarget).parent().attr('href'));
    return chrome.tabs.remove(parseInt(match[2]));
  };

  template = function(tab) {
    return "<a class='tab' href='" + tab.windowId + "#" + tab.id + "'>\n  <img class='favicon' src='" + tab.favIconUrl + "' />\n  <span class='details'>\n    <div class='title'>" + tab.title + "</div>\n    <div class='url title'>" + tab.url + "</div>\n  </span>\n</a>";
  };

  updateLabel = function() {
    var size;
    $("#count").text(size = $('.tab').size());
    $('#count').css('background', (function() {
      switch (size) {
        case 0:
          return 'firebrick';
        case 1:
          return 'orange';
        default:
          return '#999';
      }
    })());
    return doHighlight($('.tab').first());
  };

  tabs = {};

  chrome.tabs.query({}, function(result) {
    var body, key, tab, _i, _len;
    for (_i = 0, _len = result.length; _i < _len; _i++) {
      tab = result[_i];
      tabs['' + tab.id] = $(template(tab));
    }
    body = $('#tabs').html('');
    for (key in tabs) {
      tab = tabs[key];
      body.append(tab);
    }
    updateLabel();
    $('body').on('click', '.tab', selectTab).on('click', '.close', closeTab).on('mouseover', '.tab', highlightTab);
    return $('#search').keyup(function(event) {
      var list, regex;
      switch (event.which) {
        case 13:
          return $('.tab.active').click();
        case 40:
          return doHighlight($('.tab.active').next());
        case 38:
          return doHighlight($('.tab.active').prev());
        default:
          regex = new RegExp($('#search').val().replace(/\s/g, '.*'), 'i');
          list = $('#tabs').html('');
          for (key in tabs) {
            tab = tabs[key];
            if (regex.test(tab.find('.title').text())) {
              list.append(tab);
            }
          }
          return updateLabel();
      }
    });
  });

}).call(this);
