// Generated by CoffeeScript 1.3.3
(function() {
  var closeTab, doHighlight, highlightTab, selectTab, tabs, template;

  selectTab = function(event) {
    var match;
    event.preventDefault();
    match = /(\d+)#(\d+)/.exec($(event.currentTarget).attr('href'));
    console.log('Switching to tab ' + match[1] + 'in window ' + match[2]);
    chrome.windows.update(parseInt(match[1]), {
      focused: true
    });
    return chrome.tabs.update(parseInt(match[2]), {
      active: true
    });
  };

  highlightTab = function(event) {
    return doHighlight($(event.currentTarget));
  };

  doHighlight = function(tab) {
    $('.tab.active').removeClass('active');
    return tab.addClass('active');
  };

  closeTab = function(event) {
    var match;
    event.preventDefault();
    match = /(\d+)#(\d+)/.exec($(event.currentTarget).parent().attr('href'));
    return chrome.tabs.remove(parseInt(match[2]));
  };

  template = function(tab) {
    return "<a class='tab' href='" + tab.windowId + "#" + tab.id + "'>\n  <img class='favicon' src='" + tab.favIconUrl + "' />\n  <span class='details'>\n    <div class='title'>" + tab.title + "</div>\n    <div class='url title'>" + tab.url + "</div>\n  </span>\n</a>";
  };

  tabs = {};

  chrome.tabs.query({}, function(result) {
    var body, key, tab, _i, _len;
    for (_i = 0, _len = result.length; _i < _len; _i++) {
      tab = result[_i];
      tabs['' + tab.id] = $(template(tab));
    }
    body = $('#tabs').html('');
    for (key in tabs) {
      tab = tabs[key];
      body.append(tab);
    }
    doHighlight($('.tab').first());
    $('body').on('click', '.tab', selectTab).on('click', '.close', closeTab).on('mouseover', '.tab', highlightTab);
    return $('#search').keyup(function(event) {
      var list, regex;
      console.log(event.which);
      switch (event.which) {
        case 13:
          $('.tab.active').click();
          break;
        case 40:
          return doHighlight($('.tab.active').next());
        case 38:
          return doHighlight($('.tab.active').prev());
        default:
          regex = new RegExp($('#search').val().replace(/\s/g, '.*'), 'i');
          console.log('searching for ' + regex + '...');
          list = $('#tabs').text('');
          for (key in tabs) {
            tab = tabs[key];
            if (regex.test(tab.find('.title').text())) {
              list.append(tab);
            }
          }
          return doHighlight($('.tab').first());
      }
    });
  });

}).call(this);
