// Generated by CoffeeScript 1.3.3
(function() {
  var closeTab, doHighlight, filterTabs, highlightTab, resetFilter, selectTab, template, updateLabel;

  selectTab = function(event) {
    var match;
    event.preventDefault();
    match = /(\d+)#(\d+)/.exec($(event.currentTarget).attr('href'));
    console.log("Switching to tab " + match[1] + " in window " + match[2]);
    chrome.windows.update(parseInt(match[1]), {
      focused: true
    });
    return chrome.tabs.update(parseInt(match[2]), {
      active: true
    });
  };

  highlightTab = function(event) {
    return doHighlight($(event.currentTarget));
  };

  doHighlight = function(tab) {
    if (tab[0] != null) {
      $('.tab.active').removeClass('active');
      return tab.addClass('active');
    }
  };

  closeTab = function(event) {
    var match;
    event.preventDefault();
    match = /(\d+)#(\d+)/.exec($(event.currentTarget).parent().attr('href'));
    return chrome.tabs.remove(parseInt(match[2]));
  };

  template = function(tab) {
    return "<a class='tab' href='" + tab.windowId + "#" + tab.id + "'>\n  <img class='favicon' src='" + tab.favIconUrl + "' />\n  <span class='details'>\n    <div class='title'>" + tab.title + "</div>\n    <div class='url title'>" + tab.url + "</div>\n  </span>\n</a>";
  };

  updateLabel = function() {
    var size;
    $('#count').text(size = $('.tab').size()).css('background-color', (function() {
      switch (size) {
        case 0:
          return 'firebrick';
        case 1:
          return 'orange';
        default:
          return '#999';
      }
    })());
    return doHighlight($('.tab').first());
  };

  filterTabs = function(tabs) {
    var key, list, regex, tab;
    regex = new RegExp($('#search').val().replace(/\s/g, '.*'), 'i');
    list = $('#tabs').html('');
    for (key in tabs) {
      tab = tabs[key];
      if (regex.test(tab.find('.title').text())) {
        list.append(tab);
      }
    }
    return updateLabel();
  };

  resetFilter = function(tabs) {
    $('#search').val('').focus();
    return filterTabs(tabs);
  };

  chrome.tabs.query({}, function(result) {
    var body, key, tab, tabs, _i, _len;
    tabs = {};
    for (_i = 0, _len = result.length; _i < _len; _i++) {
      tab = result[_i];
      tabs['' + tab.id] = $(template(tab));
    }
    body = $('#tabs').html('');
    for (key in tabs) {
      tab = tabs[key];
      body.append(tab);
    }
    updateLabel();
    $('body').on('click', '.tab', selectTab).on('click', '.close', closeTab).on('mouseover', '.tab', highlightTab);
    $('#search').keyup(function(event) {
      var active;
      switch (event.which) {
        case 13:
          active = $('.tab.active');
          if (active.size() > 0) {
            return active.click();
          } else {
            return resetFilter(tabs);
          }
          break;
        case 38:
          return doHighlight($('.tab.active').prev());
        case 40:
          return doHighlight($('.tab.active').next());
        default:
          return filterTabs(tabs);
      }
    });
    return $('#count').click(function() {
      return resetFilter(tabs);
    });
  });

}).call(this);
